- name: Deploy main nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /opt/nginx/conf/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx container


- name: Ensure nginx config directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /opt/nginx/conf
    - /opt/nginx/conf/snippets
    - /opt/nginx/conf/sites-available
    - /opt/nginx/conf/sites-enabled

- name: Deploy proxy common snippet
  ansible.builtin.template:
    src: proxy-common.conf.j2
    dest: /opt/nginx/conf/snippets/proxy-common.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx container

- name: Deploy vhosts config
  ansible.builtin.template:
    src: vhosts.j2
    dest: /opt/nginx/conf/sites-available/services.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx container

- name: Enable services site
  ansible.builtin.file:
    src: /opt/nginx/conf/sites-available/services.conf
    dest: /opt/nginx/conf/sites-enabled/services.conf
    state: link
    force: true
  notify: Reload nginx container

- name: Remove default nginx site (if present)
  ansible.builtin.file:
    path: /opt/nginx/conf/sites-enabled/default
    state: absent
  notify: Reload nginx container
