- name: Copy K3S install script to server
  ansible.builtin.copy:
    src: ./k3s_install.sh
    dest: /tmp/k3s_install.sh
    mode: '0755'
  register: copy_result
  failed_when: "'No such file or directory' in copy_result.msg"

- name: Install K3S Server if not already installed
  ansible.builtin.command: bash /tmp/k3s_install.sh
  when: k3s_installation_status.stat.exists == false
