- name: Check if swap is enabled
  ansible.builtin.command: swapon --noheadings
  register: k3s_server_swap_status
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Disable swap if any swap is enabled
  ansible.builtin.command: swapoff -a
  become: true
  changed_when: swap_status.stdout != ""
  when: swap_status is defined and swap_status.stdout != ""


- name: Install curl
  ansible.builtin.package:
    name: curl
    state: present

- name: Download K3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /usr/local/bin/k3s-install.sh
    mode: '0755'

- name: Install K3s server
  ansible.builtin.command: /usr/local/bin/k3s-install.sh
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
  args:
    creates: /usr/local/bin/k3s

- name: Read K3s node token
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_server_k3s_token_raw

- name: Set K3s token fact
  ansible.builtin.set_fact:
    k3s_server_k3s_token: "{{ k3s_token_raw.content | b64decode | trim }}"
