- name: Check if K3S is installed
  ansible.builtin.stat:
    path: /usr/local/bin/k3s
  register: k3s_installation_status
  ignore_errors: true

- name: Install K3S server
  ansible.builtin.command: /usr/local/bin/k3s-install.sh
  args:
    creates: /usr/local/bin/k3s
  when: k3s_installation_status.stat.exists == false or "'No such file or directory' not in stderr"
