- name: Stop systemd-resolved service
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Remove /etc/resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent

- name: Create new resolv.conf pointing to AdGuard
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      nameserver 127.0.0.1
      options edns0
      nameserver {{ fallback_dns }}

- name: Change AdGuard web UI port
  ansible.builtin.replace:
    owner: 1000
    group: 1000
    mode: '0700'
    path: "{{ adguard_config_path }}"
    regexp: '^(\s*)address:.*'
    replace: '\1address: 0.0.0.0:{{ adguard_ui_port }}'
  notify: Reload adguardhome container

- name: Fix AdGuard config directory permissions
  ansible.builtin.file:
    path: "{{ adguard_conf_dir }}"
    owner: 1000
    group: 1000
    mode: '0700'
    recurse: true
    state: directory

- name: Fix file permissions inside AdGuard config
  ansible.builtin.find:
    paths: "{{ adguard_conf_dir }}"
    file_type: file
  register: adguard_files

- name: Set correct permissions on config files
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: 1000
    group: 1000
    mode: '0600'
  loop: "{{ adguard_files.files }}"

- name: Fix AdGuard work directory permissions
  ansible.builtin.file:
    path: "{{ adguard_work_dir }}"
    owner: 1000
    group: 1000
    mode: '0700'
    recurse: true
    state: directory

- name: Fix file permissions inside AdGuard work
  ansible.builtin.find:
    paths: "{{ adguard_work_dir }}"
    file_type: file
  register: adguard_work_files

- name: Set correct permissions on work files
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: 1000
    group: 1000
    mode: '0600'
  loop: "{{ adguard_work_files.files }}"
