---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: >-
      overseerr=sctx/overseerr:latest,
      jellyfin=jellyfin/jellyfin:latest,
      bazarr=linuxserver/bazarr:latest,
      radarr=linuxserver/radarr:latest,
      prowlarr=linuxserver/prowlarr:latest,
      qbittorrent=linuxserver/qbittorrent:latest,
      flaresolverr=ghcr.io/flaresolverr/flaresolverr:latest,
      scraparr=ghcr.io/thecfu/scraparr:latest,
      sonarr=linuxserver/sonarr:latest
    argocd-image-updater.argoproj.io/overseerr.update-strategy: digest
    argocd-image-updater.argoproj.io/jellyfin.update-strategy: digest
    argocd-image-updater.argoproj.io/bazarr.update-strategy: digest
    argocd-image-updater.argoproj.io/radarr.update-strategy: digest
    argocd-image-updater.argoproj.io/prowlarr.update-strategy: digest
    argocd-image-updater.argoproj.io/qbittorrent.update-strategy: digest
    argocd-image-updater.argoproj.io/flaresolverr.update-strategy: digest
    argocd-image-updater.argoproj.io/scraparr.update-strategy: digest
    argocd-image-updater.argoproj.io/sonarr.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: development
    argocd-image-updater.argoproj.io/git-credentials: argocd/git-creds
spec:
  project: default
  source:
    repoURL: https://github.com/Rami-hardware/ProxmoxInfra.git
    targetRevision: development
    path: Ansbile/argocd-apps/media
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
