---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rami-hardware/ProxmoxInfra.git
    targetRevision: development
    path: Ansbile/argocd-apps/media
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
