---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: >-
      grafana=grafana/grafana:latest,
      prometheus=prom/prometheus:latest,
      loki=grafana/loki:latest,
      alertmanager=prom/alertmanager:latest,
      speedtest-exporter=miguelndecarvalho/speedtest-exporter:latest,
      intel-gpu-exporter=ghcr.io/onedr0p/intel-gpu-exporter:rolling,
      qbittorrent-exporter=esanchezm/prometheus-qbittorrent-exporter:latest,
      blackbox-exporter=prom/blackbox-exporter:latest
    argocd-image-updater.argoproj.io/grafana.update-strategy: digest
    argocd-image-updater.argoproj.io/prometheus.update-strategy: digest
    argocd-image-updater.argoproj.io/loki.update-strategy: digest
    argocd-image-updater.argoproj.io/alertmanager.update-strategy: digest
    argocd-image-updater.argoproj.io/speedtest-exporter.update-strategy: digest
    argocd-image-updater.argoproj.io/intel-gpu-exporter.update-strategy: digest
    argocd-image-updater.argoproj.io/qbittorrent-exporter.update-strategy: digest
    argocd-image-updater.argoproj.io/blackbox-exporter.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: git@github.com:Rami-hardware/ProxmoxInfra.git
    targetRevision: main
    path: Ansbile/argocd-apps/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
