- name: Install Speedtest dependencies
  ansible.builtin.apt:
    name:
      - curl
      - tar
      - gzip
      - xz-utils
      - bzip2
      - unzip
    state: present
    update_cache: true
  become: true

- name: Download Speedtest CLI
  ansible.builtin.get_url:
    url: https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-linux-x86_64.tgz
    dest: /tmp/speedtest-cli.tgz
    mode: '0644'
  become: true

- name: Extract Speedtest CLI
  ansible.builtin.unarchive:
    src: /tmp/speedtest-cli.tgz
    dest: /usr/local/bin/
    remote_src: true
  become: true

- name: Ensure speedtest binary is executable
  ansible.builtin.file:
    path: /usr/local/bin/speedtest
    state: file
    mode: '0755'
  become: true

- name: Ensure telegraf user exists
  ansible.builtin.user:
    name: telegraf
    system: true
    create_home: true
  become: true

- name: Fix ownership of Speedtest config
  ansible.builtin.file:
    path: /home/telegraf/.config
    owner: telegraf
    group: telegraf
    recurse: true
  become: true


- name: Accept Speedtest license for telegraf
  ansible.builtin.command: /usr/local/bin/speedtest --accept-license
  become: true
  environment:
    HOME: /home/telegraf
  args:
    creates: /home/telegraf/.config/ookla/Speedtest

- name: Copy SpeedTest Telegraf config
  ansible.builtin.copy:
    src: files/speedtest.conf
    dest: "{{ telegraf_config_path }}"
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Restart Telegraf
  ansible.builtin.systemd:
    name: telegraf
    state: restarted
    enabled: true
  become: true
