- name: Download Telegraf .deb package
  ansible.builtin.get_url:
    url: https://dl.influxdata.com/telegraf/releases/telegraf_1.32.3-1_amd64.deb
    dest: /tmp/telegraf.deb
    mode: '0644'

- name: Install Telegraf from .deb
  ansible.builtin.apt:
    deb: /tmp/telegraf.deb
    state: present


- name: Install Speedtest dependencies
  ansible.builtin.apt:
    name:
      - curl
      - tar
      - gzip
      - xz-utils
      - bzip2
      - unzip
    state: present
    update_cache: true

- name: Download Speedtest CLI
  ansible.builtin.get_url:
    url: https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-linux-x86_64.tgz
    dest: /tmp/speedtest-cli.tgz
    mode: '0644'

- name: Extract Speedtest CLI
  ansible.builtin.unarchive:
    src: /tmp/speedtest-cli.tgz
    dest: /usr/local/bin/
    remote_src: true

- name: Ensure speedtest binary is executable
  ansible.builtin.file:
    path: /usr/local/bin/speedtest
    state: file
    mode: '0755'


- name: Ensure telegraf user exists
  ansible.builtin.user:
    name: telegraf
    system: true
    create_home: true

- name: Ensure Speedtest config directory exists for telegraf
  ansible.builtin.file:
    path: "{{ telegraf_home }}/.config/ookla"
    state: directory
    owner: telegraf
    group: telegraf
    mode: '0755'
    recurse: true

- name: Accept Speedtest license for telegraf
  ansible.builtin.command: /usr/local/bin/speedtest --accept-license -f json
  become: true
  become_user: telegraf
  environment:
    HOME: "{{ telegraf_home }}"
  args:
    creates: "{{ telegraf_home }}/.config/ookla/speedtest-cli.json"


- name: Ensure Telegraf config directory exists
  ansible.builtin.file:
    path: /etc/telegraf/telegraf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy SpeedTest Telegraf config
  ansible.builtin.copy:
    dest: "{{ telegraf_config_path }}"
    content: |
      [[inputs.exec]]
        commands = ["/usr/local/bin/speedtest -f json"]
        timeout = "60s"
        interval = "5m"
        data_format = "json"
    owner: root
    group: root
    mode: '0644'

- name: Restart Telegraf
  ansible.builtin.systemd:
    name: telegraf
    state: restarted
    enabled: true
