apiVersion: v1
kind: Service
metadata:
  name: osrm
  labels:
    app: osrm
spec:
  type: NodePort
  selector:
    app: osrm
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: 5000
      nodePort: {{ .Values.nodePort }}
