- name: Deploy Monitor Server Configuration
  hosts: dev-server
  become: true

  roles:
    - DNS
    - docker_setup
    - promtail
    - prometheus
    - alertmanager
    - grafana
    - loki
    - middleware
    - docker_apps
    - speed
