- name: Deploy to Gateway Server
  hosts: gateway-server
  become: true

  roles:
    # - DNS
    # - docker_setup
    # - promtail
    # - docker_apps
    - nginx_config
    # - adguard
    # - crowdsec
    - ufw
    # - k3s_agent
