- name: Deploy all Media server services
  hosts: media-server
  become: true
  roles:
    # - DNS
    # - docker_setup
    # - promtail
    - docker_apps
    # - k3s_agent
    #  - scraparr
    # - ufw
