---
- name: Deploy monitoring Server Configuration
  hosts: monitoring-server
  become: true
  roles:
    - common
    - prometheus
    - loki
    - alertmanager
    - grafana
    - promtail
    # - k3s_agent
