- name: Deploy monitoring Server Configuration
  hosts: monitoring-server
  become: true

  roles:
    - DNS
    - docker_setup
    - promtail
    - prometheus
    - alertmanager
    - grafana
    - loki
  #  - middleware
    - docker_apps
