apiVersion: v1
kind: Service
metadata:
  name: alert-forwarder
spec:
  type: NodePort
  selector:
    app: alert-forwarder
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      nodePort: {{ .Values.nodePort }}
