---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myspeed-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /opt/myspeed/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myspeed-data-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: myspeed-data-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myspeed
  namespace: monitoring
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: myspeed
  template:
    metadata:
      labels:
        app: myspeed
    spec:
      nodeSelector:
        kubernetes.io/hostname: monitoring-server
      containers:
        - name: myspeed
          image: germannewsmaker/myspeed:latest
          ports:
            - containerPort: 5216
          env:
            - name: TZ
              value: "Asia/Riyadh"
          volumeMounts:
            - name: data
              mountPath: /myspeed/data
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: myspeed-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: myspeed
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: myspeed
  ports:
    - name: http
      port: 5216
      targetPort: 5216
      nodePort: 30324
