---
- name: Remove existing Loki plugin if present
  community.docker.docker_plugin:
    plugin_name: loki
    state: absent
    force_remove: true
  failed_when: false

- name: Install Loki plugin disabled (amd64)
  ansible.builtin.command: >
    docker plugin install grafana/loki-docker-driver:3.3.2-amd64
    --alias loki
    --grant-all-permissions
    --disable
  register: docker_apps_loki_install
  changed_when: "'Installed plugin' in docker_apps_loki_install.stdout"
  failed_when: >
    docker_apps_loki_install.rc != 0 and
    'already exists' not in docker_apps_loki_install.stderr

- name: Wait for Loki plugin to appear
  ansible.builtin.command: >
    {% raw %}docker plugin ls --format '{{.Name}}'{% endraw %}
  register: docker_apps_loki_plugin_list
  retries: 6
  delay: 5
  until: "'loki' in docker_apps_loki_plugin_list.stdout"
  changed_when: false
  failed_when: false


- name: Enable Loki plugin
  community.docker.docker_plugin:
    plugin_name: loki
    state: enable

- name: Verify Loki plugin
  ansible.builtin.command: docker plugin ls
  register: docker_apps_plugin_list
  changed_when: false
