- name: Ensure scraparr dir exists
  ansible.builtin.file:
    path: "{{ scraparr_dir }}"
    state: directory
    mode: '0755'

- name: Check if config.yaml exists and is a directory
  ansible.builtin.stat:
    path: "{{ scraparr_dir }}"
  register: scraparr_config_stat

- name: Remove old config.yaml if it is a directory
  ansible.builtin.file:
    path: "{{ scraparr_dir }}"
    state: absent
  when: scraparr_config_stat.stat.isdir | default(false)

- name: Deploy Scraparr YAML config
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ scraparr_dir }}/config.yaml"
    owner: root
    group: root
    mode: '0600'
