---
apiVersion: v1
kind: Namespace
metadata:
  name: network
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  namespace: network
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      hostNetwork: true
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - "10.43.0.10"
          - "8.8.8.8"
          - "8.8.4.4"
        searches:
          - "network.svc.cluster.local"
          - "svc.cluster.local"
          - "cluster.local"
      nodeSelector:
        kubernetes.io/hostname: gateway-server
      containers:
        - name: adguard-home
          image: adguard/adguardhome:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: conf
              mountPath: /opt/adguardhome/conf
            - name: work
              mountPath: /opt/adguardhome/work
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: conf
          hostPath:
            path: /opt/adguardhome/conf
        - name: work
          hostPath:
            path: /opt/adguardhome/work
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home
  namespace: network
spec:
  type: NodePort
  externalIPs:
    - 192.168.10.200
  selector:
    app: adguard-home
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 8081
