- name: Set nginx bouncer API key fact
  ansible.builtin.set_fact:
    crowdsec_nginx_bouncer_key: "{{ crowdsec_nginx_bouncer_key_cmd.stdout | trim }}"
  when: not crowdsec_nginx_bouncer_exists

- name: Fail if nginx bouncer key is missing
  ansible.builtin.fail:
    msg: "CrowdSec nginx bouncer API key could not be created!"
  when:
    - not crowdsec_nginx_bouncer_exists
    - crowdsec_nginx_bouncer_key | default('') == ''

- name: Save nginx bouncer API key to file
  ansible.builtin.copy:
    dest: /opt/docker/crowdsec/nginx-bouncer.key
    content: "{{ crowdsec_nginx_bouncer_key }}"
    owner: root
    group: root
    mode: "0600"
  when: not crowdsec_nginx_bouncer_exists
