- name: Check if swap is enabled
  ansible.builtin.command: swapon --noheadings
  register: k3s_agent_swap_status
  changed_when: false
  failed_when: false

- name: Disable swap
  ansible.builtin.command: swapoff -a
  when: k3s_agent_swap_status.stdout | length > 0
  changed_when: k3s_agent_swap_status.stdout | length > 0

- name: Disable swap permanently in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(?!#)(.*\sswap\s.*)$'
    replace: '# \1'
  register: k3s_agent_swap_fstab

- name: Install curl
  ansible.builtin.package:
    name: curl
    state: present

- name: Download K3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /usr/local/bin/k3s-install.sh
    mode: '0755'

- name: Check if K3s is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/k3s
  register: k3s_agent_binary

- name: Install K3s agent
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s-install.sh
    creates: /usr/local/bin/k3s
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_agent_version }}"
    K3S_URL: "https://{{ hostvars['github-server']['ansible_host'] }}:6443"
    K3S_TOKEN: "{{ hostvars['github-server']['k3s_server_k3s_token'] }}"
