- name: Test nginx config inside container
  ansible.builtin.command: >
    kubectl exec -n network deployment/nginx -- nginx -t
  register: nginx_config_nginx_test
  changed_when: false
  failed_when: nginx_config_nginx_test.rc != 0

- name: Reload nginx container
  ansible.builtin.command: >
    kubectl exec -n network deployment/nginx -- nginx -s reload
  changed_when: false
