---
# handlers/main.yml
- name: Restart nginx bouncer
  ansible.builtin.service:
    name: cs-nginx-bouncer
    state: restarted

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
