apiVersion: v1
kind: Service
metadata:
  name: saudi-address
  labels:
    app: saudi-address
spec:
  type: NodePort
  selector:
    app: saudi-address
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: 8080
      nodePort: {{ .Values.nodePort }}
