apiVersion: v1
kind: Service
metadata:
  name: nominatim
  labels:
    app: nominatim
spec:
  type: NodePort
  selector:
    app: nominatim
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: 8080
      nodePort: {{ .Values.nodePort }}
