---
loki_config_dir: /opt/docker/loki
loki_http_port: 3100
loki_reject_old_samples: true
loki_reject_old_samples_max_age: 168h
loki_data_dirs:
  - /loki/index
  - /loki/boltdb-cache
  - /loki/chunks
  - /loki/compactor
  - /loki/wal
