apiVersion: v1
kind: Service
metadata:
  name: openstreetmap
  labels:
    app: openstreetmap
spec:
  type: NodePort
  selector:
    app: openstreetmap
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: 80
      nodePort: {{ .Values.nodePort }}
