sonarr:
  url: "{{ scraparr_sonarr.url }}"
  api_key: "{{ sonarr_api_key }}"
  api_version: v3

bazarr:
  url: "{{ scraparr_bazarr.url }}"
  api_key: "{{ bazarr_api_key }}"
  api_version: v3

prowlarr:
  url: "{{ scraparr_prowlarr.url }}"
  api_key: "{{ prowlarr_api_key }}"
  api_version: v3

radarr:
  url: "{{ scraparr_radarr.url }}"
  api_key: "{{ radarr_api_key }}"
  api_version: v3

overseerr:
  url: "{{ scraparr_overseerr.url }}"
  api_key: "{{ overseerr_api_key }}"
  api_version: v3
