---
- name: Check if Loki config.yml exists and is a directory
  ansible.builtin.stat:
    path: "{{ loki_config_dir }}/config.yml"
  register: loki_config_stat

- name: Remove Loki config.yml if it is a directory
  ansible.builtin.file:
    path: "{{ loki_config_dir }}/config.yml"
    state: absent
  when: loki_config_stat.stat.exists and loki_config_stat.stat.isdir

- name: Ensure Loki config directory exists
  ansible.builtin.file:
    path: "{{ loki_config_dir }}"
    state: directory
    mode: '0755'

- name: Ensure Loki data directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ loki_data_dirs }}"

- name: Template Loki config
  ansible.builtin.template:
    src: loki.yml.j2
    dest: "{{ loki_config_dir }}/config.yml"
    mode: '0644'
    force: true
