docker_apps_enabled:
  - adguardhome
  - promtail
  - fail2ban
  - nginx
  - node-exporter
  - crowdsec

service_tcp_ports:
  - 80
  - 3000
  - 8081
  - 12345
  - 3001
  - 9000
  - 443

crowdsec_ports:
  - "8080:8080"

crowdsec_acquis: ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
crowdsec_logs: logs:/var/log/nginx
crowdsec_db: crowdsec-db:/var/lib/crowdsec/data/
crowdsec_config: crowdsec-config:/etc/crowdsec/
crowdsec_collections: "crowdsecurity/nginx"

service_udp_ports:
  - 53 # AdGuard DNS

# Configuration for AdGuard Home
adguardhome_ports:
  - "3000:3000"
  - "53:53/udp"
  - "8081:80"

adguardhome_volume_config_dir: "adguard_config:/opt/adguardhome/conf"
adguardhome_volume_work_dir: "adguard_work:/opt/adguardhome/work"

# Configuration for Promtail
promtail_var_path: "/var/log:/var/log"
promtail_config_path: "{{ docker_compose_dir }}/promtail-config.yml:/etc/promtail/config.yml"

# Configuration for Nginx
nginx_ports:
  - "80:80"
  - "443:443"

nginx_default_val: "/opt/services/default.conf:/etc/nginx/conf.d/default.conf:ro"
