docker_apps_enabled:
  - adguardhome
  - promtail
  - fail2ban
  - nginx
  - node-exporter
  - authelia
service_tcp_ports:
  - 80
  - 3000
  - 8081
  - 12345
  - 3001
  - 9000
  - 443

service_udp_ports:
  - 53 # AdGuard DNS

# Configuration for AdGuard Home
adguardhome_ports:
  - "3000:3000"
  - "5353:53/udp"
  - "8081:80"

adguardhome_volume_config_dir: "adguard_config:/opt/adguardhome/conf"
adguardhome_volume_work_dir: "adguard_work:/opt/adguardhome/work"

# Configuration for Promtail
promtail_var_path: "/var/log:/var/log"
promtail_config_path: "{{ docker_compose_dir }}/promtail-config.yml:/etc/promtail/config.yml"

# Configuration for Watchtower
watchtower_run: /var/run/docker.sock:/var/run/docker.sock

# Configuration for Nginx
nginx_ports:
  - "80:80"
  - "443:443"

nginx_default_val: "/opt/services/default.conf:/etc/nginx/conf.d/default.conf:ro"

# Configuration for fail2ban
fail2ban_var_path: "/var/log:/var/log:ro"
fail2ban_data_path: "{{ docker_apps_compose_dir }}/fail2ban:/data"

authelia_config_dir: /opt/docker/authelia
authelia_secrets_dir: /opt/docker/authelia/secrets
