docker_apps_enabled:
  - adguardhome
  - promtail
  - node-exporter
  - crowdsec
  - crowdsec-nginx-bouncer

service_tcp_ports:
  - 80
  - 3000
  - 8081
  - 12345
  - 3001
  - 9000
  - 443
  - 53

adguardhome_volume_config_dir: "adguard_config:/opt/adguardhome/conf"
adguardhome_volume_work_dir: "adguard_work:/opt/adguardhome/work"

adguard_config_path: "/opt/adguardhome/conf/AdGuardHome.yaml"
adguard_conf_dir: "/opt/adguardhome/conf"
adguard_work_dir: "/opt/adguardhome/work"
adguard_ui_port: 8081
fallback_dns: 1.1.1.1

# Configuration for Promtail
promtail_var_path: "/var/log:/var/log"
promtail_config_path: "{{ docker_compose_dir }}/promtail-config.yml:/etc/promtail/config.yml"

# Configuration for Watchtower
watchtower_run: /var/run/docker.sock:/var/run/docker.sock

# Configuration for fail2ban
fail2ban_var_path: "/var/log:/var/log:ro"
fail2ban_data_path: "{{ docker_apps_compose_dir }}/fail2ban:/data"

authelia_config_dir: /opt/docker/authelia/config
authelia_cert_dir: /opt/docker/authelia/certs

authelia_container_name: authelia
authelia_image: authelia/authelia:latest

timezone: UTC

crowdsec_val:
  - /opt/docker/crowdsec/config:/etc/crowdsec
  - /opt/docker/crowdsec/data:/var/lib/crowdsec/data
  - /var/log/nginx:/var/log/nginx:ro # For Nginx logs

crowdsec_nginx_val: /opt/docker/crowdsec/bouncer:/etc/crowdsec

crowdsec_nginx_env:
  - API_URL=http://crowdsec:8080
  - API_KEY_FILE=/etc/crowdsec/bouncer_api_key

crowdsec_online_api_key: a7c65c19d023489a88b70036e3a10397nmDvrI0bzgfqoUau
crowdsec_online_api_secret: K6yiJt6KCOfj0AeXbeWQ4BptCGhEYfdCwrNwrr3NoStJ3BOGyoov7JCgbW467u3v

authelia_cluster_ip: 10.43.20.164

nginx_services:
  - name: jellyfin
    ip: 192.168.1.201
    port: 8096
    disable_buffering: true
    streaming: true
    namespace: media
    cache_paths:
      - /Items
      - /web
    cache_ttl: "7d"

  - name: overseerr
    ip: 192.168.1.201
    port: 5055
    namespace: media

  - name: adguard
    ip: 192.168.1.200
    port: 8081
    namespace: network
    k8s_service: adguard-home

nginx_services_local:
  - name: jellyfin
    namespace: media
    ip: 192.168.1.201
    port: 8096
    disable_buffering: true
    streaming: true
    cache_paths:
      - /Items
      - /web
    cache_ttl: "7d"

  - name: overseerr
    ip: 192.168.1.201
    port: 5055
    namespace: media

  - name: radarr
    ip: 192.168.1.201
    port: 7878
    namespace: media
    auth: false

  - name: sonarr
    ip: 192.168.1.201
    port: 8989
    namespace: media
    auth: false

  - name: prowlarr
    ip: 192.168.1.201
    port: 9696
    namespace: media
    auth: false

  - name: bazarr
    ip: 192.168.1.201
    port: 6767
    namespace: media
    auth: false

  - name: qbittorrent
    ip: 192.168.1.201
    port: 8080
    disable_buffering: true
    namespace: media
    auth: false

  - name: adguard
    ip: 192.168.1.200
    port: 8081
    namespace: network
    k8s_service: adguard-home
    auth: false

  - name: grafana
    ip: 192.168.1.203
    port: 3000
    namespace: monitoring
    auth: false

  - name: alertmanager
    ip: 192.168.1.203
    port: 9093
    namespace: monitoring
    auth: false

  - name: prometheus
    ip: 192.168.1.203
    port: 9090
    namespace: monitoring
    auth: false

  - name: router
    ip: 192.168.1.1
    port: 80
    namespace: network
    auth: false

  - name: server
    ip: 192.168.1.250
    port: 8006
    namespace: network
    auth: false
    backend_protocol: HTTPS
