---
prometheus_retention_time: 30d

k3s_apps_list:
  - name: overseerr
    namespace: media
    image: sctx/overseerr:latest
    external_ip: 192.168.1.201
    port: 5055
    node_port: 5055
    target_node: media-server
    config_path: /opt/overseer
    config_mount: /app/config
    replicas: 1
    env:
      - { name: TZ, value: "Asia/Riyadh" }
    memory_request: "256Mi"
    memory_limit: "1Gi"
    cpu_request: "200m"
    cpu_limit: "1000m"

  - name: jellyfin
    namespace: media
    image: jellyfin/jellyfin:latest
    external_ip: 192.168.1.201
    port: 8096
    node_port: 8096
    target_node: media-server
    config_path: /opt/jellyfin
    config_mount: /config
    replicas: 1
    gpu: true
    extra_volumes:
      - name: media
        host_path: /mnt/media
        mount_path: /media
      - name: cache
        host_path: /opt/jellyfin/cache
        mount_path: /cache
    env:
      - { name: TZ, value: "Asia/Riyadh" }
      - { name: LIBVA_DRIVER_NAME, value: "iHD" }
      - { name: VAAPI_DEVICE, value: "/dev/dri/renderD128" }
      - { name: JELLYFIN_HWACCEL, value: "vaapi" }
    memory_request: "512Mi"
    memory_limit: "4Gi"
    cpu_request: "500m"
    cpu_limit: "3000m"

  - name: bazarr
    namespace: media
    image: linuxserver/bazarr:latest
    external_ip: 192.168.1.201
    port: 6767
    node_port: 6767
    target_node: media-server
    config_path: /opt/bazarr
    config_mount: /config
    replicas: 1
    extra_volumes:
      - name: tv
        host_path: /mnt/media/tv
        mount_path: /tv
      - name: movies
        host_path: /mnt/media/movies
        mount_path: /movies
    env:
      - { name: TZ, value: "Asia/Riyadh" }
      - { name: PUID, value: "1000" }
      - { name: PGID, value: "1000" }
    memory_request: "256Mi"
    memory_limit: "1Gi"
    cpu_request: "200m"
    cpu_limit: "1000m"

  - name: radarr
    namespace: media
    image: linuxserver/radarr:latest
    external_ip: 192.168.1.201
    port: 7878
    node_port: 7878
    target_node: media-server
    config_path: /opt/radarr
    config_mount: /config
    replicas: 1
    extra_volumes:
      - name: movies
        host_path: /mnt/media/movies
        mount_path: /movies
      - name: download
        host_path: /mnt/media/download
        mount_path: /downloads
    env:
      - { name: TZ, value: "Asia/Riyadh" }
      - { name: PUID, value: "1000" }
      - { name: PGID, value: "1000" }
    memory_request: "256Mi"
    memory_limit: "1Gi"
    cpu_request: "200m"
    cpu_limit: "1000m"

  - name: prowlarr
    namespace: media
    image: linuxserver/prowlarr:latest
    external_ip: 192.168.1.201
    port: 9696
    node_port: 9696
    target_node: media-server
    config_path: /opt/prowlarr
    config_mount: /config
    replicas: 1
    env:
      - { name: TZ, value: "Asia/Riyadh" }
      - { name: PUID, value: "1000" }
      - { name: PGID, value: "1000" }
    memory_request: "128Mi"
    memory_limit: "512Mi"
    cpu_request: "100m"
    cpu_limit: "500m"

  - name: qbittorrent
    namespace: media
    external_ip: 192.168.1.201
    image: linuxserver/qbittorrent:latest
    port: 8080
    node_port: 8080
    target_node: media-server
    config_path: /opt/qbittorrent
    config_mount: /config
    replicas: 1
    extra_volumes:
      - name: downloads
        host_path: /mnt/media/download
        mount_path: /downloads
    env:
      - { name: TZ, value: "Asia/Riyadh" }
      - { name: PUID, value: "1000" }
      - { name: PGID, value: "1000" }
      - { name: WEBUI_PORT, value: "8080" }
    memory_request: "256Mi"
    memory_limit: "2Gi"
    cpu_request: "200m"
    cpu_limit: "2000m"

  - name: flaresolverr
    namespace: media
    image: ghcr.io/flaresolverr/flaresolverr:latest
    external_ip: 192.168.1.201
    port: 8191
    node_port: 8191
    target_node: media-server
    skip_pv: true
    replicas: 1
    env:
      - { name: TZ, value: "Asia/Riyadh" }
      - { name: LOG_LEVEL, value: "info" }
    memory_request: "512Mi"
    memory_limit: "2Gi"
    cpu_request: "200m"
    cpu_limit: "1000m"

  - name: subsyncarr
    namespace: media
    image: mrorbitman/subsyncarr:latest
    target_node: media-server
    config_path: /opt/subsyncarr
    external_ip: 192.168.1.201
    config_mount: /config
    replicas: 1
    extra_volumes:
      - name: movies
        host_path: /mnt/media/movies
        mount_path: /movies
      - name: media
        host_path: /mnt/media/tv
        mount_path: /tv
    env:
      - { name: TZ, value: "Asia/Riyadh" }
      - { name: PUID, value: "1000" }
      - { name: PGID, value: "1000" }
      - { name: SCAN_PATHS, value: "/movies,/tv" }
      - { name: MAX_CONCURRENT_SYNC_TASKS, value: 1 }
      - { name: INCLUDE_ENGINES, value: ffsubsync }
      - { name: DOWNLOAD_SUBS, value: false }
      - { name: FFMPEG_HWACCEL, value: vaapi }
    memory_request: "128Mi"
    memory_limit: "512Mi"
    cpu_request: "100m"
    cpu_limit: "500m"

  - name: scraparr
    namespace: media
    image: ghcr.io/thecfu/scraparr
    external_ip: 192.168.1.201
    port: 7100
    node_port: 7100
    target_node: media-server
    config_path: /opt/scraparr/config
    config_mount: /scraparr/config
    replicas: 1
    env:
      - { name: TZ, value: "Asia/Riyadh" }
    memory_request: "128Mi"
    memory_limit: "512Mi"
    cpu_request: "100m"
    cpu_limit: "500m"

  - name: intel-gpu-exporter
    namespace: monitoring
    external_ip: 192.168.1.203
    image: ghcr.io/onedr0p/intel-gpu-exporter:rolling
    port: 8080
    node_port: 8082
    target_node: media-server
    skip_pv: true
    privileged: true
    replicas: 1
    extra_volumes:
      - name: dri
        host_path: /dev/dri
        mount_path: /dev/dri
    env:
      - { name: TZ, value: "Asia/Riyadh" }
    memory_request: "64Mi"
    memory_limit: "256Mi"
    cpu_request: "50m"
    cpu_limit: "200m"

  - name: qbittorrent-exporter
    namespace: monitoring
    external_ip: 192.168.1.201
    image: caseyscarborough/qbittorrent-exporter:latest
    port: 17871
    node_port: 17871
    target_node: media-server
    skip_pv: true
    replicas: 1
    env:
      - name: QBITTORRENT_USERNAME
        value: "{{ qbittorrent_exporter_username }}"
      - name: QBITTORRENT_PASSWORD
        value: "{{ qbittorrent_exporter_password }}"
      - name: QBITTORRENT_BASE_URL
        value: "{{ qbittorrent_exporter_base_url }}"
    memory_request: "64Mi"
    memory_limit: "256Mi"
    cpu_request: "50m"
    cpu_limit: "200m"

  - name: sonarr
    namespace: media
    image: linuxserver/sonarr:latest
    external_ip: 192.168.1.201
    port: 8989
    node_port: 8989
    target_node: media-server
    config_path: /opt/sonarr
    config_mount: /config
    replicas: 1
    extra_volumes:
      - name: tv
        host_path: /mnt/media/tv
        mount_path: /tv
      - name: download
        host_path: /mnt/media/download
        mount_path: /downloads
    env:
      - { name: TZ, value: "Asia/Riyadh" }
      - { name: PUID, value: "1000" }
      - { name: PGID, value: "1000" }
    memory_request: "256Mi"
    memory_limit: "1Gi"
    cpu_request: "200m"
    cpu_limit: "1000m"

  - name: grafana
    namespace: monitoring
    image: grafana/grafana:latest
    external_ip: 192.168.1.203
    port: 3000
    node_port: 3000
    target_node: monitoring-server
    config_path: /opt/docker/grafana
    config_mount: /opt/docker/grafana
    replicas: 1
    extra_volumes:
      - name: provisioning
        host_path: /opt/docker/grafana/provisioning
        mount_path: /etc/grafana/provisioning
    env:
      - { name: GF_PATHS_DATA, value: /opt/docker/grafana }
    memory_request: "128Mi"
    memory_limit: "512Mi"
    cpu_request: "50m"
    cpu_limit: "500m"

  - name: prometheus
    namespace: monitoring
    image: prom/prometheus:latest
    external_ip: 192.168.1.203
    port: 9090
    node_port: 9090
    target_node: monitoring-server
    service_account: prometheus
    config_path: /opt/docker/prometheus
    config_mount: /etc/prometheus
    replicas: 1
    args:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time={{ prometheus_retention_time }}"
      - "--web.enable-lifecycle"
    memory_request: "256Mi"
    memory_limit: "1Gi"
    cpu_request: "100m"
    cpu_limit: "1000m"

  - name: loki
    namespace: monitoring
    image: grafana/loki:latest
    external_ip: 192.168.1.203
    port: 3100
    node_port: 3100
    target_node: monitoring-server
    config_path: /opt/docker/loki
    config_mount: /etc/loki
    replicas: 1
    args:
      - "-config.file=/etc/loki/config.yml"
    memory_request: "128Mi"
    memory_limit: "512Mi"
    cpu_request: "50m"
    cpu_limit: "500m"

  - name: alertmanager
    namespace: monitoring
    image: prom/alertmanager:latest
    external_ip: 192.168.1.203
    port: 9093
    node_port: 9093
    target_node: monitoring-server
    config_path: /opt/docker/alertmanager
    config_mount: /etc/alertmanager
    replicas: 1
    args:
      - "--config.file=/etc/alertmanager/config.yml"
    memory_request: "64Mi"
    memory_limit: "256Mi"
    cpu_request: "25m"
    cpu_limit: "200m"

  - name: speedtest-exporter
    namespace: monitoring
    image: miguelndecarvalho/speedtest-exporter
    external_ip: 192.168.1.203
    port: 9798
    node_port: 9798
    target_node: monitoring-server
    skip_pv: true
    dns_policy: None
    dns_nameservers:
      - "8.8.8.8"
      - "8.8.4.4"
    replicas: 1
    memory_request: "64Mi"
    memory_limit: "256Mi"
    cpu_request: "25m"
    cpu_limit: "200m"

  - name: nginx
    namespace: network
    image: nginx:latest
    target_node: gateway-server
    skip_pv: true
    host_network: true
    dns_policy: None
    dns_nameservers:
      - "8.8.8.8"
      - "8.8.4.4"
    replicas: 1
    external_ip: 192.168.1.200
    port: 80
    node_port: 8181
    extra_volumes:
      - name: nginx-conf
        host_path: /opt/nginx/conf/nginx.conf
        mount_path: /etc/nginx/nginx.conf
        read_only: true
      - name: conf-d
        host_path: /opt/nginx/conf/conf.d
        mount_path: /etc/nginx/conf.d
        read_only: true
      - name: snippets
        host_path: /opt/nginx/conf/snippets
        mount_path: /etc/nginx/snippets
        read_only: true
      - name: logs
        host_path: /opt/nginx/logs
        mount_path: /var/log/nginx
      - name: sites-enabled
        host_path: /opt/nginx/conf/sites-enabled
        mount_path: /etc/nginx/sites-enabled
        read_only: true
      - name: certs
        host_path: /opt/nginx/certs
        mount_path: /etc/nginx/certs
        read_only: true
    memory_request: "64Mi"
    memory_limit: "256Mi"
    cpu_request: "25m"
    cpu_limit: "200m"

  - name: adguard-home
    namespace: network
    image: adguard/adguardhome:latest
    target_node: gateway-server
    skip_pv: true
    host_network: true
    dns_policy: None
    dns_nameservers:
      - "8.8.8.8"
      - "8.8.4.4"
    replicas: 1
    port: 3000
    node_port: 8081
    external_ip: 192.168.1.200
    extra_ports:
      - port: 53
        protocol: TCP
      - port: 53
        protocol: UDP
    extra_volumes:
      - name: conf
        host_path: /opt/adguardhome/conf
        mount_path: /opt/adguardhome/conf
      - name: work
        host_path: /opt/adguardhome/work
        mount_path: /opt/adguardhome/work
    memory_request: "64Mi"
    memory_limit: "256Mi"
    cpu_request: "25m"
    cpu_limit: "200m"
