authelia_local_namespaces:
  - media
  - network
  - monitoring

authelia_session_secret: "{{ vault_authelia_session_secret }}"
authelia_encryption_key: "{{ vault_authelia_encryption_key }}"
authelia_jwt_secret: "{{ vault_authelia_jwt_secret }}"

authelia_users:
  - username: rami
    displayname: "Rami"
    email: ramidannah5@gmail.com
    password_hash: "{{ vault_authelia_password_hash }}"
    groups:
      - admins
