---
- name: Check if Alertmanager config.yml exists and is a directory
  ansible.builtin.stat:
    path: "{{ alertmanager_config_dir }}/config.yml"
  register: alertmanager_config_stat

- name: Remove Alertmanager config.yml if it is a directory
  ansible.builtin.file:
    path: "{{ alertmanager_config_dir }}/config.yml"
    state: absent
  when: alertmanager_config_stat.stat.isdir | default(false)

- name: Ensure Alertmanager config directory exists
  ansible.builtin.file:
    path: "{{ alertmanager_config_dir }}"
    state: directory
    mode: '0755'

- name: Template Alertmanager config
  ansible.builtin.template:
    src: alertmanager.yml.j2
    dest: "{{ alertmanager_config_dir }}/config.yml"
    mode: '0644'
